name: Web-Deploy Jaaxs

on:
  workflow_dispatch

jobs:
  web-deploy:
    name: Web-Deploy Jaaxs
    runs-on: ubuntu-latest

    steps:
      - id: CHECKOUT_REPO
        name: Checkout Repo
        uses: actions/checkout@v2

      - id: SETUP_NODE
        name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - id: INSTALL_HUGO_AND_CLOUD_CLI
        name: Install Surge and Hugo
        run: npm install -g surge hugo-bin

      - id: INSTALL_NODE_DEPENDENCIES
        name: Install Dependencies
        run: npm install

      - id: BUILD_HUGO_STATIC_HTML
        name: Build Static HTML
        run: hugo
